// Texts of the access screens in English (docs/landing-spec.md §8), key by key the Spanish deck of
// copy-es.ts. Same rules: no limit written by hand, no consent text (consent-texts.ts owns them).
import type { AuthCopy } from "./copy";

export const AUTH_EN: AuthCopy = {
  lang: {
    code: "en",
    switchTo: "Español",
    switchLabel: "Ver la página en español",
  },
  layout: {
    tagline: "Coordination agent for customs brokerage firms",
    title: "Every file complete before arrival.",
    lead: "Commercial invoice, packing list and certificate of origin: the agent asks the importer on WhatsApp and the supplier by email, decides who fixes each finding and leaves the file ready for you to approve.",
    points: ["Approval is always yours", "Contact policy in code", "100 % synthetic data in this demo"],
    backHome: "Back to the home page",
    privacy: "Privacy",
    terms: "Terms",
    newTab: "(opens in a new tab)",
  },
  titles: {
    signup: "Create account · Legajo listo",
    verify: "Verify your email · Legajo listo",
    login: "Sign in · Legajo listo",
    forgot: "Reset your password · Legajo listo",
    reset: "New password · Legajo listo",
    welcome: "Preparing your world · Legajo listo",
  },
  signup: {
    title: "Try Legajo listo",
    lead: "Create your account and in a minute you get your own fictitious firm, with operation 4471 ready to walk through. All with synthetic data.",
    email: "Work email",
    emailHint: "We will send you a code to verify it.",
    password: "Password",
    optionalGroup: "Tell us about you (optional)",
    name: "Name",
    company: "Company",
    jobTitle: "Job title",
    consentContactHint: "Optional. You can withdraw it at any time.",
    submit: "Create account",
    submitting: "Sending…",
    haveAccount: "Already have an account? Sign in",
    syntheticNote: "In the demo you only work with fictitious companies and people. Do not enter real data about your firm or your clients.",
    honeypot: "Do not fill in this field",
    errors: {
      email: "Enter a valid email.",
      password: "The password does not meet the rules below.",
      tooLong: (max: number) => `Use at most ${max} characters.`,
      consentTerms: "To create the account you need to accept the terms and the privacy policy.",
      summary: (count: number) => `Check ${count} ${count === 1 ? "field" : "fields"} before continuing.`,
      generic: "We could not send the form. Try again in a few minutes.",
      staleTexts: "The legal texts changed while you had the page open. Reload it to read the current ones and send again.",
      reload: "Reload the page",
    },
    retryNotice: "We had to reload the page to verify your browser. Your details are still here: type your password again and send.",
  },
  verify: {
    title: "Check your email",
    lead: (email: string, digits: number) =>
      `If the email can be used, we sent a ${digits}-digit code to ${email}. It may take a couple of minutes; check your spam folder too.`,
    existingHintBefore: "If you already have an account, ",
    existingHintLink: "sign in",
    existingHintAfter: '. If you got a "You already have an account" email, its code confirms the password you just chose.',
    code: "Verification code",
    password: "Type the password you chose again",
    submit: "Verify",
    submitting: "Verifying…",
    resend: "Resend code",
    resendIn: (seconds: number) => `You can request another code in ${seconds} s`,
    resendReady: "You can request another code now.",
    resent: "Done: if the email can be used, a new code is on its way. The previous one no longer works.",
    resendWait: (minutes: number) => `Wait ${minutes} min before requesting another code.`,
    resendExhausted: "We cannot resend more codes for this sign-up. Check your spam folder or start again.",
    changeEmail: "Change email",
    missing: "We could not find a sign-up in progress in this tab. Start again and we will send you a code.",
    errors: {
      invalid: "The code is not valid or has expired. Check it or request a new one.",
      attemptsLeft: (count: number) => `You have ${count} attempts left.`,
      expired: "This sign-up can no longer be completed: the code expired or there were too many attempts. Start again and we will send you a new code.",
    },
    restart: "Start again",
    done: "Your email is verified. Sign in to prepare your world.",
  },
  login: {
    title: "Sign in to Legajo listo",
    lead: "With your account email or the username you were given.",
    login: "Email or username",
    password: "Password",
    submit: "Sign in",
    submitting: "Signing in…",
    forgot: "I forgot my password",
    noAccount: "No account? Try Legajo listo",
    errors: {
      credentials: "The email, username or password is not correct.",
      tooMany: "Too many attempts. Wait a few minutes and try again.",
      unconfirmed: "Your email still needs verifying. If we can, we will send you a new code.",
      unconfirmedRestart: "Your email still needs verifying. Complete the sign-up again and we will send you a code.",
    },
    notices: {
      reset: "Done: your password changed. Sign in with the new one.",
      sessionExpired: "Your session expired. Please sign in again.",
      signedOut: "You signed out.",
      welcome: "Your email is verified. Sign in to prepare your world.",
    },
    unconfiguredTitle: "Sign-in not configured",
    unconfiguredLead: "This build lacks the user pool details. Without them there is no sign-in.",
  },
  welcome: {
    title: "Preparing your world",
    lead: "We are creating your fictitious firm with synthetic data. It takes a few seconds.",
    preparing: "Preparing…",
    includesTitle: "What you will find",
    includes: ["Your fictitious firm", "Importers and suppliers", "Operation 4471 and five more", "The clock paused on 14/10 at 10:30"],
    expired: (inactiveHours: number, maxAgeHours: number) =>
      `Your previous world was deleted: ${inactiveHours} h went by without use, or ${maxAgeHours} h since we created it. We are preparing a new one from day 0.`,
    ttl: (inactiveHours: number, maxAgeHours: number) =>
      `Your demo world is deleted after ${inactiveHours} h without use or ${maxAgeHours} h after it was created. Your account stays: when you come back, we prepare a new one.`,
    capacity: {
      title: "The demo is full",
      lead: "The demo is full right now. Your account is already created: try again later.",
      note: "When you sign in again, we will try again. If you would like to see it with someone from the team, let's talk.",
      talk: "Let's talk",
    },
    retry: "Try again",
    failed: {
      title: "We could not prepare your world",
      lead: 'Try again. If it happens again, write to us through "Let\'s talk".',
      talk: "Let's talk",
    },
    signOut: "Sign out",
  },
  quota: {
    day: (what: string, time: string) => `You reached this demo's limit for today (${what}); it resets at ${time}.`,
    hour: (what: string, time: string) => `You reached this demo's limit for this hour (${what}); it resets at ${time}.`,
    global: (time: string) => `The demo reached its usage limit for today; it resets at ${time}.`,
    usage: "Your demo's usage",
    usageLine: (used: number, limit: number) => `${used} of ${limit}`,
    globalExhausted: "The demo reached its usage limit for today.",
    dismiss: "Got it",
    kinds: {
      AGENT_TURNS: "agent turns",
      OUTBOUND_EMAILS: "outgoing emails",
      SIMULATOR_MESSAGES: "simulator messages",
      CLOCK_MOVES: "clock moves",
      PDF_UPLOADS: "PDF uploads",
      NEW_OPERATIONS: "new operations",
      WORLD_RESETS: "world resets",
      LIVE_CLOCK: "live clock",
      WORLD_PREPARATIONS: "world preparations",
    },
  },
  forgot: {
    title: "Reset your password",
    lead: "Enter your account email and we will send you a code.",
    email: "Email",
    submit: "Send code",
    sent: "If there is an account with that detail, we sent you a code. It may take a couple of minutes.",
  },
  reset: {
    title: "Choose a new password",
    email: "Your account email",
    code: "Code",
    password: "New password",
    submit: "Change password",
    errors: { invalid: "The code is not valid or has expired. Request a new one." },
    back: "Back to sign in",
  },
  signOut: {
    action: "Sign out",
    dismiss: "Dismiss",
  },
  states: {
    rateLimited: (minutes: number) => `We received many requests in a row. Try again in ${minutes} min.`,
    rateLimitedEdge: "We received many requests in a row from your connection. Wait a few minutes and try again.",
    challenge: "We could not verify your browser: reload the page or turn off your content blocker.",
    signupPaused: 'New sign-ups are paused for a while. Try again later or write to us through "Let\'s talk".',
    offline: "There seems to be no connection. Check it and try again.",
    unexpected: (id: string) => `Something went wrong. Try again. Reference code: ${id}`,
    talk: "Let's talk",
  },
  password: {
    show: "Show",
    hide: "Hide",
    rulesTitle: "The password needs:",
    rules: {
      length: (min: number) => `${min} characters or more`,
      lower: "a lowercase letter",
      upper: "an uppercase letter",
      number: "a number",
      symbol: "a symbol (for example ! # $ -)",
    },
    confirm: "Repeat the password",
    mismatch: "The two passwords do not match.",
    outerSpaces: "The password cannot start or end with a space.",
  },
  steps: {
    newPassword: {
      title: "Choose your password",
      lead: "This is your first sign-in: replace the temporary password with your own.",
      field: "New password",
      submit: "Save and continue",
    },
    mfaSetup: {
      title: "Turn on the verification code",
      leadRequired: "Your account asks for the verification code (TOTP). It is set up once.",
      leadOptional: "It is optional and adds a layer of security to your user. It is set up once.",
      steps: [
        "Open your authenticator app: any app that supports TOTP codes.",
        "Scan the QR code, or enter the key by hand.",
        "Type the code the app shows you.",
      ],
      qrLabel: "QR code for your authenticator app",
      manualKey: "Key to enter by hand",
      code: "Code from the app",
      submit: "Turn on",
      skip: "Not now",
    },
    totp: {
      title: "Verification code",
      lead: "Type the code your authenticator app shows.",
      code: "Code",
      submit: "Verify",
    },
    back: "Back to sign in",
    otherUser: "Sign in with another user",
    working: "One moment…",
  },
  flowErrors: {
    INVALID_CREDENTIALS: "The email, username or password is not correct.",
    UNCONFIRMED: "Your email still needs verifying. If we can, we will send you a new code.",
    INVALID_CODE: "The code is not valid or has expired. Try the one it shows now.",
    WEAK_PASSWORD: "The password does not meet the requirements.",
    SESSION_EXPIRED: "Too much time went by. Start again with your user and password.",
    TOO_MANY_ATTEMPTS: "Too many attempts. Wait a few minutes and try again.",
    UNAVAILABLE: "We could not reach the sign-in service. Check your connection and try again.",
    UNSUPPORTED: "Your user asks for a verification method the console does not support. Ask the broker for help.",
    DIFFERENT_USER: "That is not the user of this session. Confirm with yours.",
  },
  prompts: {
    stepUp: {
      title: "Confirm it is you",
      lead: "Approving or reopening a file needs a recent sign-in. Confirm with your password.",
      done: "Done. You can try the action again.",
    },
    enroll: {
      title: "Verification code",
      done: "Code turned on. We will ask for it from your next sign-in.",
      unavailable: "We could not prepare the verification code. Try again in a few seconds.",
      retry: "Try again",
    },
    changePassword: {
      title: "Change password",
      lead: "Confirm your current password and choose a new one. The session stays open.",
      current: "Current password",
      field: "New password",
      same: "The new password has to be different from the current one.",
      submit: "Change password",
      done: "Done: your password changed. Next time sign in with the new one.",
      wrongCurrent: "The current password is not correct.",
    },
    close: "Close",
  },
};
