// Texts of the access screens in Rioplatense Spanish (docs/landing-spec.md §8): sign-up, code,
// sign-in, recovery, the guest world being prepared, usage limits, sign-out and the global states,
// plus the steps of the staff sign-in (first password, TOTP) and the console's security prompts.
// No limit is written here: every duration, cap or count arrives as an argument, from
// packages/shared/src/guest-limits.ts or from the BFF's answer (D-12). The two consent texts are not
// here either: packages/shared/src/consent-texts.ts is their only source.

export const AUTH_ES = {
  lang: {
    /** `<html lang>` of the page. */
    code: "es-AR",
    switchTo: "English",
    switchLabel: "Ver la página en inglés",
  },
  layout: {
    tagline: "Agente de coordinación para estudios de despachantes de aduana",
    title: "Cada legajo completo antes del arribo.",
    lead: "Factura comercial, packing list y certificado de origen: el agente los pide al importador por WhatsApp y al proveedor por email, decide quién corrige cada observación y te deja el legajo listo para aprobar.",
    points: ["La aprobación es siempre tuya", "Política de contacto en código", "Datos 100 % sintéticos en esta demo"],
    backHome: "Volver al inicio",
    privacy: "Privacidad",
    terms: "Términos",
    newTab: "(se abre en una pestaña nueva)",
  },
  titles: {
    signup: "Crear cuenta · Legajo listo",
    verify: "Verificá tu email · Legajo listo",
    login: "Ingresar · Legajo listo",
    forgot: "Recuperar contraseña · Legajo listo",
    reset: "Nueva contraseña · Legajo listo",
    welcome: "Preparando tu mundo · Legajo listo",
  },
  signup: {
    title: "Probá Legajo listo",
    lead: "Creá tu cuenta y en un minuto tenés un estudio ficticio propio, con la operación 4471 lista para recorrer. Todo con datos sintéticos.",
    email: "Email de trabajo",
    emailHint: "Te enviamos un código para verificarlo.",
    password: "Contraseña",
    optionalGroup: "Contanos de vos (opcional)",
    name: "Nombre",
    company: "Empresa",
    jobTitle: "Cargo",
    consentContactHint: "Opcional. Podés retirarlo cuando quieras.",
    submit: "Crear cuenta",
    submitting: "Enviando…",
    haveAccount: "¿Ya tenés cuenta? Ingresá",
    syntheticNote: "En la demo operás solo sobre empresas y personas ficticias. No cargues datos reales de tu estudio ni de tus clientes.",
    honeypot: "No completes este campo",
    errors: {
      email: "Escribí un email válido.",
      password: "La contraseña no cumple las reglas de arriba.",
      tooLong: (max: number) => `Usá como máximo ${max} caracteres.`,
      consentTerms: "Para crear la cuenta tenés que aceptar los términos y la política de privacidad.",
      summary: (count: number) => `Revisá ${count} campo(s) antes de seguir.`,
      generic: "No pudimos enviar el formulario. Probá de nuevo en unos minutos.",
      staleTexts: "Los textos legales cambiaron mientras tenías la página abierta. Recargala para leer los vigentes y volvé a enviar.",
      reload: "Recargar la página",
    },
    retryNotice: "Tuvimos que recargar la página para verificar tu navegador. Tus datos siguen acá: escribí de nuevo la contraseña y enviá.",
  },
  verify: {
    title: "Revisá tu email",
    lead: (email: string, digits: number) =>
      `Si el email puede usarse, te enviamos un código de ${digits} dígitos a ${email}. Puede tardar un par de minutos; mirá también en spam.`,
    existingHintBefore: "Si ya tenés una cuenta, ",
    existingHintLink: "ingresá",
    existingHintAfter: ". Si te llegó un email de «Ya tenés una cuenta», su código confirma la contraseña que acabás de elegir.",
    code: "Código de verificación",
    password: "Volvé a escribir la contraseña que elegiste",
    submit: "Verificar",
    submitting: "Verificando…",
    resend: "Reenviar código",
    resendIn: (seconds: number) => `Podés pedir otro código en ${seconds} s`,
    resendReady: "Ya podés pedir otro código.",
    resent: "Listo: si el email puede usarse, te llega un código nuevo. El anterior ya no vale.",
    resendWait: (minutes: number) => `Esperá ${minutes} min antes de pedir otro código.`,
    resendExhausted: "Ya no podemos reenviar más códigos para esta alta. Revisá spam o empezá de nuevo.",
    changeEmail: "Cambiar email",
    missing: "No encontramos un alta en curso en esta pestaña. Empezá de nuevo y te mandamos un código.",
    errors: {
      invalid: "El código no es válido o venció. Revisalo o pedí uno nuevo.",
      attemptsLeft: (count: number) => `Te quedan ${count} intentos.`,
      expired: "Esta alta ya no se puede completar: el código venció o hubo demasiados intentos. Empezá de nuevo; te mandamos un código nuevo.",
    },
    restart: "Empezar de nuevo",
    done: "Tu email quedó verificado. Ingresá para preparar tu mundo.",
  },
  login: {
    title: "Ingresá a Legajo listo",
    lead: "Con el email de tu cuenta o el usuario que te dieron.",
    login: "Email o usuario",
    password: "Contraseña",
    submit: "Ingresar",
    submitting: "Ingresando…",
    forgot: "Olvidé mi contraseña",
    noAccount: "¿No tenés cuenta? Probá la demo",
    errors: {
      credentials: "El email, el usuario o la contraseña no son correctos.",
      tooMany: "Hiciste muchos intentos. Esperá unos minutos y probá de nuevo.",
      unconfirmed: "Falta verificar tu email. Si podemos, te mandamos un código nuevo.",
      unconfirmedRestart: "Falta verificar tu email. Completá el alta de nuevo y te mandamos un código.",
    },
    notices: {
      reset: "Listo: tu contraseña cambió. Ingresá con la nueva.",
      sessionExpired: "La sesión venció. Ingresá de nuevo.",
      signedOut: "Cerraste sesión.",
      welcome: "Tu email quedó verificado. Ingresá para preparar tu mundo.",
    },
    unconfiguredTitle: "Ingreso sin configurar",
    unconfiguredLead: "Este build no tiene los datos del grupo de usuarios. Sin ellos no hay ingreso.",
  },
  welcome: {
    title: "Preparando tu mundo",
    lead: "Estamos creando tu estudio ficticio con datos sintéticos. Tarda unos segundos.",
    preparing: "Preparando…",
    includesTitle: "Qué vas a encontrar",
    includes: ["Tu estudio ficticio", "Importadores y proveedores", "La operación 4471 y cinco más", "El reloj en pausa el 14/10 a las 10:30"],
    expired: (inactiveHours: number, maxAgeHours: number) =>
      `Tu mundo anterior se borró: pasaron ${inactiveHours} h sin uso o ${maxAgeHours} h desde que lo creamos. Te preparamos uno nuevo desde el día 0.`,
    ttl: (inactiveHours: number, maxAgeHours: number) =>
      `Tu mundo de demo se borra después de ${inactiveHours} h sin uso o a las ${maxAgeHours} h de creado. Tu cuenta sigue: al volver, te preparamos uno nuevo.`,
    capacity: {
      title: "La demo está completa",
      lead: "La demo está completa en este momento. Tu cuenta ya está creada: probá de nuevo más tarde.",
      note: "Cuando vuelvas a ingresar, lo intentamos de nuevo. Si querés verlo con alguien del equipo, hablemos.",
      talk: "Hablemos",
    },
    retry: "Probar de nuevo",
    failed: {
      title: "No pudimos preparar tu mundo",
      lead: "Probá de nuevo. Si vuelve a pasar, escribinos desde «Hablemos».",
      talk: "Hablemos",
    },
    signOut: "Cerrar sesión",
  },
  quota: {
    day: (what: string, time: string) => `Llegaste al límite de esta demo por hoy (${what}); se renueva a las ${time}.`,
    hour: (what: string, time: string) => `Llegaste al límite de esta demo por esta hora (${what}); se renueva a las ${time}.`,
    global: (time: string) => `La demo llegó a su límite de uso de hoy; se renueva a las ${time}.`,
    usage: "Uso de tu demo",
    usageLine: (used: number, limit: number) => `${used} de ${limit}`,
    globalExhausted: "La demo llegó a su límite de uso de hoy.",
    dismiss: "Entendido",
    kinds: {
      AGENT_TURNS: "turnos del agente",
      OUTBOUND_EMAILS: "emails salientes",
      SIMULATOR_MESSAGES: "mensajes del simulador",
      CLOCK_MOVES: "movimientos del reloj",
      PDF_UPLOADS: "cargas de PDF",
      NEW_OPERATIONS: "operaciones nuevas",
      WORLD_RESETS: "reinicios del mundo",
      LIVE_CLOCK: "reloj en vivo",
      WORLD_PREPARATIONS: "preparaciones del mundo",
    },
  },
  forgot: {
    title: "Recuperá tu contraseña",
    lead: "Escribí el email de tu cuenta y te enviamos un código.",
    email: "Email",
    submit: "Enviar código",
    sent: "Si hay una cuenta con ese dato, te enviamos un código. Puede tardar un par de minutos.",
  },
  reset: {
    title: "Elegí una contraseña nueva",
    email: "Email de tu cuenta",
    code: "Código",
    password: "Contraseña nueva",
    submit: "Cambiar contraseña",
    errors: { invalid: "El código no es válido o venció. Pedí uno nuevo." },
    back: "Volver a ingresar",
  },
  signOut: {
    action: "Cerrar sesión",
    dismiss: "Cerrar aviso",
  },
  states: {
    rateLimited: (minutes: number) => `Recibimos muchos pedidos seguidos. Probá de nuevo en ${minutes} min.`,
    rateLimitedEdge: "Recibimos muchos pedidos seguidos desde tu conexión. Esperá unos minutos y probá de nuevo.",
    challenge: "No pudimos verificar tu navegador: recargá la página o desactivá el bloqueador de contenido.",
    signupPaused: "Las altas nuevas están en pausa por un rato. Probá de nuevo más tarde o escribinos desde «Hablemos».",
    offline: "Parece que no hay conexión. Revisala y probá de nuevo.",
    unexpected: (id: string) => `Algo salió mal. Probá de nuevo. Código de referencia: ${id}`,
    talk: "Hablemos",
  },
  password: {
    show: "Mostrar",
    hide: "Ocultar",
    rulesTitle: "La contraseña necesita:",
    rules: {
      length: (min: number) => `${min} caracteres o más`,
      lower: "una minúscula",
      upper: "una mayúscula",
      number: "un número",
      symbol: "un símbolo (por ejemplo ! # $ -)",
    },
    confirm: "Repetí la contraseña",
    mismatch: "Las dos contraseñas no coinciden.",
    outerSpaces: "La contraseña no puede empezar ni terminar con un espacio.",
  },
  steps: {
    newPassword: {
      title: "Elegí tu contraseña",
      lead: "Es tu primer ingreso: reemplazá la contraseña temporal por una propia.",
      field: "Contraseña nueva",
      submit: "Guardar y seguir",
    },
    mfaSetup: {
      title: "Activá el código de verificación",
      leadRequired: "Tu cuenta pide el código de verificación (TOTP). Se configura una sola vez.",
      leadOptional: "Es opcional y suma una capa de seguridad a tu usuario. Se configura una sola vez.",
      steps: [
        "Abrí tu app de autenticación: cualquier app compatible con códigos TOTP.",
        "Escaneá el código QR, o cargá la clave a mano.",
        "Escribí el código que te muestra la app.",
      ],
      qrLabel: "Código QR para tu app de autenticación",
      manualKey: "Clave para cargar a mano",
      code: "Código de la app",
      submit: "Activar",
      skip: "Ahora no",
    },
    totp: {
      title: "Código de verificación",
      lead: "Escribí el código que muestra tu app de autenticación.",
      code: "Código",
      submit: "Verificar",
    },
    back: "Volver al ingreso",
    otherUser: "Ingresar con otro usuario",
    working: "Un momento…",
  },
  flowErrors: {
    INVALID_CREDENTIALS: "El email, el usuario o la contraseña no son correctos.",
    UNCONFIRMED: "Falta verificar tu email. Si podemos, te mandamos un código nuevo.",
    INVALID_CODE: "El código no es válido o ya venció. Probá con el que muestra ahora.",
    WEAK_PASSWORD: "La contraseña no cumple los requisitos.",
    SESSION_EXPIRED: "Pasó demasiado tiempo. Empezá de nuevo con tu usuario y tu contraseña.",
    TOO_MANY_ATTEMPTS: "Hiciste muchos intentos. Esperá unos minutos y probá de nuevo.",
    UNAVAILABLE: "No pudimos comunicarnos con el servicio de ingreso. Revisá tu conexión y reintentá.",
    UNSUPPORTED: "Tu usuario pide un método de verificación que la consola no admite. Pedile ayuda al despachante.",
    DIFFERENT_USER: "Ese no es el usuario de esta sesión. Confirmá con el tuyo.",
  },
  prompts: {
    stepUp: {
      title: "Confirmá que sos vos",
      lead: "Aprobar o reabrir un legajo pide haber ingresado hace poco. Confirmá con tu contraseña.",
      done: "Listo. Ya podés volver a intentar la acción.",
    },
    enroll: {
      title: "Código de verificación",
      done: "Código activado. Desde el próximo ingreso te lo vamos a pedir.",
      unavailable: "No pudimos preparar el código de verificación. Reintentá en unos segundos.",
      retry: "Reintentar",
    },
    changePassword: {
      title: "Cambiar contraseña",
      lead: "Confirmá la contraseña actual y elegí una nueva. La sesión sigue abierta.",
      current: "Contraseña actual",
      field: "Contraseña nueva",
      same: "La contraseña nueva tiene que ser distinta de la actual.",
      submit: "Cambiar contraseña",
      done: "Listo: tu contraseña cambió. La próxima vez ingresá con la nueva.",
      wrongCurrent: "La contraseña actual no es correcta.",
    },
    close: "Cerrar",
  },
} as const;
