/// <reference path="../../sst-env.d.ts" />
// Typed access to what SST links into a Lambda (`Resource`, never `process.env`). Names are the
// logical SST names of infra/storage-tables.ts, infra/storage-buckets.ts (docs/architecture.md §5-§6)
// and infra/channel-modes.ts; the physical names arrive at runtime through the link.
//
// `sst-env.d.ts` is generated by `sst deploy`, so its `Resource` augmentation is empty until the
// stage has been brought up. Reading through this module keeps every consumer typed against the
// logical names and validates the linked shape with zod at first use, whatever the generated file
// says.
import { Resource } from "sst";
import { z } from "zod";
import { ChannelMode, ChannelName, ConnectorError } from "@legajo/shared";

export const TABLE_NAMES = [
  "Firms",
  "Parties",
  "Operations",
  "Conversations",
  "AuditLog",
  "Reference",
  "Runtime",
  "LegajoMetrics",
  "ReaderCatalog",
  "Platform",
] as const;
export type TableName = (typeof TABLE_NAMES)[number];

export const BUCKET_NAMES = ["Documents", "Uploads", "Media", "Seed", "InboundMail"] as const;
export type BucketName = (typeof BUCKET_NAMES)[number];

const NamedResource = z.object({ name: z.string().min(1) });
const ChannelModesResource = z.object({
  email: ChannelMode,
  whatsapp: ChannelMode,
});
export type ChannelModes = z.infer<typeof ChannelModesResource>;

const cache = new Map<string, unknown>();

// `Resource` is a Proxy that throws when a property was not linked to this function. Reading it
// through Reflect keeps the value `unknown` until zod has checked the shape.
export function readLinked<T>(logicalName: string, schema: z.ZodType<T>): T {
  const cached = cache.get(logicalName);
  if (cached !== undefined) return schema.parse(cached);
  let raw: unknown;
  try {
    raw = Reflect.get(Resource, logicalName);
  } catch (error) {
    throw new ConnectorError("UNAVAILABLE", `resource "${logicalName}" is not linked to this function`, logicalName, { cause: error });
  }
  const parsed = schema.safeParse(raw);
  if (!parsed.success) {
    throw new ConnectorError("UNAVAILABLE", `resource "${logicalName}" has an unexpected shape`, logicalName, { cause: parsed.error });
  }
  cache.set(logicalName, parsed.data);
  return parsed.data;
}

/** Physical DynamoDB table name of a logical table (`Resource.<Table>.name`). */
export function tableName(table: TableName): string {
  return readLinked(table, NamedResource).name;
}

/** Physical S3 bucket name of a logical bucket (`Resource.<Bucket>.name`). */
export function bucketName(bucket: BucketName): string {
  return readLinked(bucket, NamedResource).name;
}

export function channelModes(): ChannelModes {
  return readLinked("ChannelModes", ChannelModesResource);
}

export function channelMode(name: ChannelName): ChannelMode {
  return channelModes()[name];
}

/** Stage flags are the only values read from the environment (CLAUDE.md). */
export function currentStage(): string {
  return process.env.STAGE ?? Resource.App.stage;
}

/** Test seam: forget cached links (used by vitest between cases). */
export function resetResourceCache(): void {
  cache.clear();
}
