// English texts of the registry, with exactly the shape of the Spanish in copy-es.ts (`satisfies`).
import type { Widen } from "../../copy/localized";
import type { RegistryCopy, behaviourEs, contactStatusEs, docTypeEs, languageEs, mediumEs } from "./copy-es";

export const en = {
  importers: {
    title: "Importers",
    description: "Every importer with their WhatsApp contact, the opt-in and which suppliers they authorized the agent to write to.",
    add: "New importer",
    empty: "The world has no importers.",
    name: "Importer",
    phone: "Phone",
    consent: "WhatsApp opt-in",
    authorizations: "Authorization to write to the supplier",
    actions: "Actions",
    edit: "Edit",
    editLabel: (name: string) => `Edit the importer ${name}`,
    consentAction: "Opt-in",
    consentLabel: (name: string) => `WhatsApp opt-in of ${name}`,
    authorize: "Authorizations",
    authorizeLabel: (name: string) => `Authorizations of ${name}`,
    noAuthorizations: "No authorizations",
  },
  consent: {
    none: "No opt-in",
    granted: (at: string, medium: string, version: string) => `In force since ${at} · ${medium} · text ${version}`,
    revoked: (at: string) => `Revoked on ${at}`,
    title: (name: string) => `WhatsApp opt-in · ${name}`,
    lead: "Without an opt-in in force no WhatsApp goes out to this importer. The record keeps the date, the medium and the version of the text they were shown.",
    medium: "Medium",
    grantedAt: "Date of consent",
    grantedAtHint: "Argentina simulated time.",
    textVersion: "Version of the text shown",
    record: "Record opt-in",
    revokeTitle: "Revoke the opt-in",
    revokeLead: "The next WhatsApp the agent attempts is denied by the opt-out (notice opt-out rule).",
    reason: "Reason (optional)",
    revoke: "Revoke opt-in",
    recorded: "Opt-in recorded.",
    revoked_: "Opt-in revoked.",
  },
  authorization: {
    title: (name: string) => `Authorizations · ${name}`,
    lead: "Without the importer's authorization the agent does not write to the supplier (authorization to write to the supplier rule).",
    none: "The firm has no suppliers loaded.",
    authorized: "Authorized",
    notAuthorized: "Not authorized",
    authorizedSince: (at: string) => `Authorized since ${at}`,
    grant: (supplier: string) => `Authorize contact with ${supplier}`,
    revoke: (supplier: string) => `Remove authorization for ${supplier}`,
    grantShort: "Authorize contact",
    revokeShort: "Remove authorization",
    saved: "Authorization updated.",
  },
  importerForm: {
    newTitle: "New importer",
    editTitle: (name: string) => `Edit · ${name}`,
    name: "Company name",
    contactName: "Contact (full name)",
    contactFirstName: "Contact's first name",
    phone: "Phone (international format)",
    phoneHint: "With the country code, for example +5491155500101. A phone belongs to a single contact.",
    phoneKeep: "Leave it empty to keep the registered phone.",
    phoneInvalid: "Write the phone in international format: + and between 8 and 15 digits.",
    submit: "Save importer",
    saved: "Importer saved.",
  },
  suppliers: {
    title: "Suppliers",
    description: "Every supplier with their email contacts, time zone, language and the behaviour of the simulated supplier.",
    add: "New supplier",
    empty: "The world has no suppliers.",
    name: "Supplier",
    timezone: "Time zone",
    language: "Language",
    contacts: "Contacts",
    behaviour: "Simulated behaviour",
    profile: "Measured profile",
    noProfile: "No measurements yet",
    replies: (hours: string, count: number) => `Replies in ~${hours} h (${count === 1 ? "1 reply" : `${count} replies`})`,
    bounces: (count: number) => (count === 1 ? "1 bounce" : `${count} bounces`),
    late: (documents: string) => `Usually late with: ${documents}`,
    actions: "Actions",
    edit: "Edit",
    editLabel: (name: string) => `Edit the supplier ${name}`,
    addContact: "Add contact",
    addContactLabel: (name: string) => `Add a contact to ${name}`,
    setBehaviour: "Behaviour",
    setBehaviourLabel: (name: string) => `Simulated behaviour of ${name}`,
    confirm: "Confirm",
    confirmLabel: (email: string) => `Confirm the contact ${email}`,
    noContacts: "No contacts",
    confirmed: "Contact confirmed.",
  },
  supplierForm: {
    newTitle: "New supplier",
    editTitle: (name: string) => `Edit · ${name}`,
    name: "Company name",
    country: "Country (2-letter code)",
    countryInvalid: "Use the country's 2-letter code, for example CN.",
    timezone: "IANA time zone",
    timezoneHint: "For example Asia/Shanghai: emails to the supplier respect their business hours.",
    timezoneInvalid: "That time zone does not exist.",
    contacts: "Contact emails (one per line)",
    contactsHint: "A contact loaded by the firm is active. In the demo only simulated mailboxes of the simulation domain or the SES bounce simulator are accepted.",
    emailInvalid: "There is an email with an invalid format.",
    submit: "Save supplier",
    saved: "Supplier saved.",
  },
  contactForm: {
    title: (name: string) => `New contact · ${name}`,
    email: "Email",
    hint: "It is active, loaded by the firm. It has to pass the demo's recipient fence.",
    submit: "Add contact",
    saved: "Contact added.",
  },
  behaviourForm: {
    title: (name: string) => `Simulated behaviour · ${name}`,
    lead: "How the simulated supplier replies to the agent's emails. It only replies to our own verified mail.",
    behaviour: "Behaviour",
    scope: "For",
    allOperations: "All their operations",
    operation: (number: string) => `Only operation ${number}`,
    submit: "Save behaviour",
    saved: "Behaviour saved.",
  },
  forms: {
    close: "Close",
    cancel: "Cancel",
    required: "Fill in this field.",
  },
  reasons: {
    RECIPIENT_NOT_ALLOWED: "That address does not pass the demo's recipient fence: use a simulated mailbox of the simulation domain or the SES bounce simulator.",
    CONFLICT: "That phone or email already belongs to another contact or another firm.",
    GUEST_SYNTHETIC_ONLY: "Your trial world only keeps fictitious data: phones from your world's numbering block (like those of the importers it already has) and simulated mailboxes of the simulation domain.",
  },
} satisfies RegistryCopy;

export const mediumEn = {
  SIGNED_FORM: "Signed form",
  EMAIL: "Email",
  IN_PERSON: "In person",
} satisfies Widen<typeof mediumEs>;

export const contactStatusEn = {
  PENDING_CONFIRMATION: "Pending confirmation",
  ACTIVE: "Active",
  BOUNCED: "Bounced",
  COMPLAINED: "Complained",
} satisfies Widen<typeof contactStatusEs>;

export const behaviourEn = {
  PROMPT: "Replies right away with the correct documents",
  SEEDED_ERROR: "First with a seeded error, then corrected",
  SEEDED_ERROR_TWICE: "Twice with the same error, then corrected",
  LATE: "Replies late",
  NEVER: "Does not reply",
  WRONG_DOC: "Sends another document instead of the one requested",
  UNKNOWN_DOC: "Sends a PDF the reader does not know",
  PROMISE: "Promises to send it the next day",
  AUTO_REPLY: "Out-of-office auto-reply, then replies",
  INJECTION: "Tries to inject instructions",
  BOUNCE: "Bounces (SES simulator)",
  COMPLAINT: "Recipient complaint (SES simulator)",
} satisfies Widen<typeof behaviourEs>;

export const docTypeEn = {
  COMMERCIAL_INVOICE: "commercial invoice",
  PACKING_LIST: "packing list",
  CERTIFICATE_OF_ORIGIN: "certificate of origin",
} satisfies Widen<typeof docTypeEs>;

export const languageEn = { es: "Spanish", en: "English" } satisfies Widen<typeof languageEs>;
