// English texts of the public landing (docs/landing-spec.md §2), with the same type as the Spanish ones
// (copy-es.ts): a key missing here does not compile. Plain English; a decimal point and a comma for
// thousands. What the importer reads on WhatsApp stays in Spanish, with its fixed English gloss.
import { labelsEn } from "@legajo/bff/copy/en";
import { OBSERVATION_LABELS } from "@legajo/bff/copy/observation-labels";
import type { ObservationCode } from "@legajo/shared";
import { formatNumber } from "../../lib/format";
import type { LandingCopy } from "./copy-es";
import { MEDIA_EN } from "./media-copy-en";

export const en: LandingCopy = {
  meta: {
    code: "en",
    title: "Legajo listo · Coordination agent for customs brokers",
    description: "Every import file complete before the vessel arrives: an agent that chases the commercial invoice, the packing list and the certificate of origin of every import.",
  },
  lang: { switchTo: "Español", switchLabel: "Ver la página en español" },
  nav: { label: "Page sections", tour: "How it works", guarantees: "Guarantees", integrations: "Integration", demo: "What is simulated", faq: "Questions", menu: "Menu", skip: "Skip to content" },
  cta: {
    try: "Try the demo",
    tryShort: "Try",
    signIn: "Sign in",
    talk: "Let's talk",
    toConsole: "Go to my console",
    talkHint: "Opens Craftech's contact page in a new tab",
    newTab: "(opens in a new tab)",
  },
  motion: { paused: "Pause animations", resume: "Resume animations" },
  session: { signedIn: "You have an open session." },
  hero: {
    eyebrow: "For customs brokerage firms",
    title: "Every import file complete before the vessel arrives.",
    lead: "Legajo listo chases the commercial invoice, the packing list and the certificate of origin of every import: the importer on WhatsApp, the foreign supplier by email, in English. It decides who must fix each finding, reschedules deadlines when the ETA moves and leaves the file ready for you to approve.",
    primary: "Try the demo",
    secondary: "Sign in",
    tertiary: "See how it works",
    trust: ["Approval is always yours", "Contact policy in code", "Serverless on AWS"],
    note: "Demo with 100% synthetic data: your own fictitious firm, ready in a minute.",
    phoneCaption: "Simulator: the texts are the real template texts; the firm is fictitious.",
    replay: "Replay the conversation",
    phoneLabel: "Sample WhatsApp conversation between Estudio Delta and an importer",
  },
  problem: {
    eyebrow: "The problem",
    title: "Three documents, two languages and a vessel that does not wait",
    lead: "Before arrival, the broker needs the complete file. The documents are with the importer or, almost always, with a foreign supplier who answers in English, from another time zone and by email.",
    items: [
      { title: "Manual chasing", text: "Messages from a personal phone, forwarded emails, and nobody knows what was asked, of whom or when." },
      { title: "Late fixes with no owner", text: "A weight mismatch shows up with the vessel in port, and the importer gets a problem that is not theirs." },
      { title: "The ETA moves", text: "The arrival changes, deadlines go stale and the storage and demurrage risk stays hidden until it costs." },
    ],
    timeline: { label: "Days to arrival", marks: ["ETA − 7", "ETA − 3", "ETA − 48 h", "Arrival"] },
  },
  tour: {
    eyebrow: "How it works",
    title: "Operation 4471, end to end",
    lead: "A fictitious importer brings textiles on the vessel Austral Aurora, arriving on 22/10. The invoice is already valid; the packing list and the certificate of origin are missing. This is how Legajo listo handles it.",
    stepLabel: (at: number, of: number): string => `Step ${at} of ${of}`,
    previous: "Previous step",
    next: "Next step",
    stepsLabel: "Tour steps",
    carousel: "carousel",
    simTime: "Simulated time",
    agentSample: "Sample agent text",
    template: "Approved template",
    fixed: "Fixed text",
    renderBadge: "Animation built with the product's components and texts",
    enlarge: "Enlarge",
    steps: {
      request: { channel: "WhatsApp · template", title: "The first request, seven days before arrival", text: "The importer gets what is missing with four buttons: upload the documents, have the supplier send them, ask a question or stop the notices." },
      delegate: { channel: "WhatsApp · contact policy", title: '"The supplier will send them"', text: "The importer delegates with one tap and confirms the registered contact. It is 9 p.m. on the other side: the email waits until 9 a.m. supplier time, and the agent tells the importer." },
      supplier: { channel: "Email · in English", title: "What the supplier receives", text: "A clear request, in English, from the operation's address. The supplier replies in the same thread with the PDFs attached." },
      reader: { channel: "Document reader", title: "What the reader finds", text: "Every PDF goes to the document reader through its contract. The certificate is valid; the packing list states 12,480 kg gross weight and the invoice, 12,840 kg." },
      owner: { channel: "Email · WhatsApp", title: "Who must fix it", text: 'The fix belongs to the supplier: the agent asks for it in the same thread. The importer only hears what concerns them: "nothing for you to do".' },
      eta: { channel: "Carrier · milestones", title: "The ETA moves two days earlier", text: "The carrier reports a new arrival. The code reschedules the pending milestones, without the model, and the agent communicates the new deadline." },
      escalation: { channel: "Guardrail · escalation", title: "What is not the agent's call goes to the broker", text: '"Which tariff heading applies?" is customs advice. A guardrail stops it before the model, the importer gets a fixed answer and the broker gets an escalation notice with the context.' },
      approval: { channel: "Firm console", title: "Approval is always human", text: "Version 2 of the packing list arrives and the file is ready for review. With all three documents valid, the broker reviews readings and findings and approves after a recent sign-in. No agent tool can approve." },
    },
    eta: {
      before: "Before",
      after: "Now",
      milestone: "Milestone",
      event: "The carrier reports a new estimated arrival: 22/10 → 20/10.",
      tableLabel: "Milestones rescheduled by the code",
      milestones: { followupFinal: "Final reminder (ETA − 3 days)", escalation: "Escalation if anything is missing (ETA − 48 h)", arrival: "Arrival" },
    },
    reader: { title: "Document reader result", found: "on the packing list", expected: "on the invoice", owner: "Owner", pending: "—", version: (version: number): string => `version ${version}` },
    deferral: { supplier: "Deferred by the supplier's working hours until 9 a.m. their time", importer: "Deferred by Argentina's hours until 9 a.m." },
    escalation: { guardrail: "Guardrail before the model", model: "Model", blocked: "Stopped", mailbox: "Firm mailbox" },
    approval: { approved: "Approved by a person", recentSignIn: "Asks for a sign-in within the last 15 minutes" },
  },
  capabilities: {
    eyebrow: "What it does",
    title: "Every party, on their channel and in their language",
    importer: {
      title: "Importer",
      lead: "Knows what is theirs to do and what is not.",
      items: ["WhatsApp request with buttons", "Upload link with no username or password", "Delegate to the supplier with one tap", "Questions answered from the firm's checklist", "Opt out of notices at any time"],
    },
    supplier: { title: "Foreign supplier", lead: "A clear request, in English and in their working hours.", items: ["English email from the operation's address", "Specific fixes in the same thread", "Never outside their working hours"] },
    firm: {
      title: "Brokerage firm",
      lead: "Complete files before arrival, with the reason for every step.",
      items: ["Operations with their next event", "File detail with readings, findings and owners", "Escalations by reason", "Take over the conversation at any time", "Approve, always a person", "Metrics with their N and a decision log"],
    },
  },
  guarantees: {
    eyebrow: "Guarantees",
    title: "What does not depend on the model",
    lead: "The model decides what to do on each turn. What is not negotiable lives in the code, in the agent's policies and in the guardrails.",
    ruleLabel: "Rule",
    items: [
      { title: "Approval is always human.", text: "No agent tool can approve, and the console asks for a recent sign-in." },
      { title: "The contact policy lives in code.", text: "Opt-in, 24-hour window, each party's hours and one reminder a day, checked before every send." },
      { title: "Nobody gets someone else's data.", text: "Every send goes through a recipient fence and no message carries outside links or contacts." },
      { title: "Document reading belongs to your reader.", text: "Every PDF goes to the document reader through its contract; what it cannot recognise goes to the broker." },
      { title: "The model does not decide identity.", text: "The importer's registered phone; the operation's address, a confirmed contact and DMARC for the supplier." },
      { title: "Everything inbound is hostile.", text: "Sensitive data masked before storage and a guardrail before the model." },
    ],
    rules: {
      "CED-NO-APPROVE": "The agent does not approve",
      "CP-OPTIN": "WhatsApp opt-in",
      "CP-HOURS-AR": "Argentina's hours",
      "CP-HOURS-SUPPLIER": "Supplier's hours",
      "CP-ONE-PER-DAY": "One reminder a day",
      "CP-NO-FOREIGN-LINKS": "No outside links or contacts",
    },
  },
  impact: {
    eyebrow: "Impact",
    title: "What we aim for in your firm",
    lead: "This is a demo: we show no production results. These are design goals, and the console measures each one in your world, with its N.",
    labels: { goal: "Goal", guarantee: "Guaranteed in code", assumption: "Assumption" },
    tiles: {
      complete72h: { value: (count: number): string => `${count} h`, title: "File complete before arrival", note: "All three documents valid at least 72 hours before the current ETA." },
      sameDay: { value: (): string => "Same day", title: "Every fix, asked of its owner", note: "When the PDF arrives, the finding goes to whoever must fix it, that same day." },
      oneStory: { value: (count: number): string => `${count}%`, title: "One story per operation", note: "Every request, reply, reading and decision on one timeline, with its reason." },
      humanApproval: { value: (count: number): string => `${count}%`, title: "Approvals made by a person", note: "No agent tool can approve." },
    },
    footnote: "Your demo's numbers are measured in the console, with their N, source and label: measured, scripted agent or assumption.",
    assumptions: "Demurrage risk is estimated with assumptions each firm can edit (free days in port, USD per day and per container).",
  },
  integrations: {
    eyebrow: "How it integrates",
    title: "Serverless on AWS, connected to your systems by contract",
    lead: "AWS channels to talk to each party, an agent with rules in code and contract-based connectors to your document reader and your management system.",
    lanes: { channels: "Channels", agent: "Agent", time: "Time and events", systems: "Your systems" },
    nodes: {
      whatsapp: "WhatsApp through AWS End User Messaging Social · approved templates, buttons and documents",
      email: "Amazon SES · sending and receiving, DMARC and one thread per operation",
      upload: "Upload link · no account, with malware scanning",
      agentcore: "Amazon Bedrock AgentCore · turns, tools, policies and memory",
      guardrails: "Amazon Bedrock Guardrails · before the model and on every outgoing text",
      scheduler: "Amazon EventBridge Scheduler · ETA-relative milestones that reschedule themselves",
      reader: "Document reader · the one your firm chooses, behind an OpenAPI contract",
      platform: "Your management system · contract-based connector, adapted to your firm",
    },
    points: ["No servers to manage", "Contract-based connectors", "Everything as infrastructure as code"],
    platforms: {
      title: "For trade-software platforms",
      lead: "Do you build software for customs brokers or importers? Legajo listo plugs in as a module, without replacing what you already do.",
      items: [
        "The document reader connects through a published OpenAPI contract",
        "The management platform, through a versioned API with its schema",
        "Statuses and updates come in as events",
        "Channels, contact policy and rules live in code, on AWS serverless",
      ],
      cta: "Let's talk about integrating it",
    },
    diagramAlt:
      "Diagram: the importer on WhatsApp and the supplier by email reach a per-operation queue; the agent on Bedrock AgentCore decides with tools and policies; sends leave through a pipeline with the contact policy; the document reader and the management system connect by contract.",
  },
  demo: {
    eyebrow: "In this demo",
    title: "What is real and what is simulated",
    columns: {
      real: { title: "Real.", text: "Amazon SES end to end, Amazon Bedrock AgentCore and Guardrails, EventBridge Scheduler, SQS, DynamoDB, S3, Cognito and CloudFront." },
      simulatedMode: { title: "Built, running in simulated mode.", text: "AWS End User Messaging Social, the WhatsApp adapter: tested with fixtures; in the demo you use a phone simulator inside the console." },
      mocks: { title: "Simulated systems.", text: "Document reader, customs management system, carrier, customs and suppliers (with their own mailboxes)." },
      data: { title: "Data.", text: "100% synthetic. Firms, importers, suppliers, vessels and people are fictitious." },
    },
    clock: "Your demo's clock is paused: simulated time moves with a button, so you see in minutes what takes days.",
  },
  faq: {
    eyebrow: "Questions",
    title: "Frequently asked questions",
    data: {
      q: "Where do my importers' documents live, and who sees them?",
      a: "On AWS, region us-east-1 (United States). Before storage, sensitive data (tax IDs, national IDs, bank accounts, cards, IBAN) is masked. Only your firm sees each operation; every party gets only what concerns them, and the agent works on the masked text. In this demo everything is synthetic.",
    },
    reader: {
      q: "What if my firm does not use a document reader?",
      a: "Legajo listo does not read documents on its own: every PDF goes to a document reader through an OpenAPI contract. If you do not use one yet, we choose it together and Craftech adapts it to that contract during the pilot. Whatever the reader cannot recognise goes to the broker.",
    },
    platform: { q: "How does it connect to my management system?", a: "Through a contract-based connector adapted to each firm: it reads the operation's data and receives status changes as events. In this demo, the management system is simulated." },
    whatsapp: {
      q: "What do I need to use WhatsApp?",
      a: "Your firm's own business number, message templates approved by the channel operator and each importer's consent (opt-in). Messages go out through AWS End User Messaging Social and are billed per use. In this demo the channel runs in simulated mode, with a phone simulator.",
    },
    cost: { q: "How much does it cost?", a: "It depends on your firm's volume of operations and on AWS usage (agent turns, emails and messages). Tell us how you work today and we will plan the pilot together.", cta: "Let's talk" },
    approval: { q: "Who approves the file?", a: "Always a person: the broker, from the console and after a recent sign-in. No agent tool can approve." },
  },
  gallery: {
    eyebrow: "The console",
    title: "Everything that happened, with its reason",
    lead: "Captures of the real console over a synthetic world.",
    renderNote: "Animation built with the product's components and texts",
    localNote: "Local environment, scripted agent",
    placeholderNote: "Provisional image",
  },
  zoom: {
    open: (alt: string): string => `Enlarge image: ${alt}`,
    close: "Close",
    previous: "Previous image",
    next: "Next image",
    counter: (at: number, of: number): string => `${at} of ${of}`,
    actualSize: "Actual size",
  },
  media: MEDIA_EN,
  closing: {
    title: "Your trial firm, ready in a minute",
    lead: "Create your account, get a fictitious firm with operation 4471 and walk through the story at your own pace, with the clock in your hands.",
    try: "Try the demo",
    talkAlt: "or write to sales@craftech.io",
    signIn: "I have an account: sign in",
    talkTitle: "Want it for your firm?",
    talkLead: "Tell us how you work today and we will look at it together.",
    talk: "Let's talk",
  },
  footer: { product: "Legajo listo · Powered by Craftech", synthetic: "Demo with 100% synthetic data: every name is fictitious.", legal: "Legal", privacy: "Privacy", terms: "Terms", contact: "Contact", rights: "© 2026 Craftech" },
  phone: {
    simulator: "Simulator · WhatsApp in simulated mode",
    fictitious: "fictitious firm",
    glossToggle: "Show the English gloss",
    glossButton: "English gloss",
    typing: "typing…",
    conversation: (day: string): string => `WhatsApp conversation of ${day}`,
    transcript: "Full conversation",
  },
  email: {
    threadLabel: "Email thread with the supplier",
    from: "From",
    to: "To",
    subject: "Subject",
    agent: "Sample body: the agent writes it",
    simulator: "Real text of the simulated supplier",
    when: (ar: string, supplier: string): string => `${ar} in Buenos Aires · ${supplier} in Qingdao`,
  },
  labels: labelsEn,
  observation: (code: ObservationCode): string => OBSERVATION_LABELS[code].en,
  kg: (value: number): string => `${formatNumber(value).replace(/\./g, ",")} kg`,
};
