// Texts of the escalations inbox (docs/design-brief.md §6, row 3). Rioplatense Spanish, for the firm.

export const escalationsCopy = {
  caption: "Escalamientos abiertos, el más antiguo primero",
  filter: "Motivo",
  all: "Todos",
  columns: {
    operation: "Operación",
    reason: "Motivo",
    summary: "Resumen",
    opened: "Abierto",
    by: "Por",
  },
  openFor: (days: number, hours: number) => (days > 0 ? `hace ${days} d ${hours} h` : `hace ${hours} h`),
  empty: {
    title: "No hay escalamientos abiertos",
    lead: "Cuando el agente o el sistema derivan algo al estudio, aparece acá con su motivo.",
  },
  emptyFiltered: "Ningún escalamiento abierto con ese motivo",
  open: (number: string) => `Escalamiento de la operación ${number}`,
  drawer: {
    operation: (number: string) => `Operación ${number}`,
    reason: "Motivo",
    summary: "Resumen",
    noSummary: "Sin resumen.",
    opened: (when: string, by: string) => `Abierto el ${when} por ${by}`,
    viewDossier: "Ver el legajo",
    take: "Tomar conversación",
    taking: "Tomando…",
    takeLead: "Tomar la conversación deja al agente en pausa en esta operación y abre el legajo para escribirle al importador.",
    resolveTitle: "Resolver",
    resolution: "Cómo se resolvió",
    resolutionHint: "Queda en la bitácora con tu usuario y la hora simulada.",
    resolutionRequired: "Escribí cómo se resolvió.",
    resolve: "Resolver",
    resolving: "Resolviendo…",
    resolved: "Escalamiento resuelto.",
    close: "Cerrar",
  },
} as const;
