// English texts of the dossier view, key by key the Spanish ones of copy-es.ts (`satisfies` refuses a
// missing, extra or differently typed key). The assumptions of the risk are always labelled
// "assumption", as the Spanish labels them "supuesto".
import type { DossierCopy } from "./copy-es";
import type { BrokerTemplate } from "./dossier-model";

export const en = {
  notFound: {
    title: "This operation does not exist",
    lead: "Check the link or go back to the list of operations.",
  },
  back: "Back to operations",
  actions: "Dossier actions",
  heading: (number: string, importer: string, supplier: string) => `Operation ${number} · ${importer} · ${supplier}`,
  sections: {
    nav: "Dossier sections",
    summary: "Summary",
    documents: "Documents",
    pending: "Pending items",
    timeline: "Timeline",
  },
  facts: {
    eta: "ETA",
    toArrival: "To arrival",
    dossier: "Dossier",
    control: "Conversation",
    dispatch: "Dispatch",
    risk: "Risk",
    toArrivalValue: (days: number, hours: number) => (days > 0 ? `${days} d ${hours} h` : `${hours} h`),
    arrived: "Already arrived",
    unknown: "—",
  },
  parties: {
    title: "Parties and operation details",
    importer: "Importer",
    supplier: "Supplier",
    contact: (name: string, phone: string) => `${name} · ${phone}`,
    supplierZone: (country: string, zone: string) => `${country} · local time: ${zone}`,
    contacts: "Supplier contacts",
    noContacts: "No contacts on record",
    contactStatus: {
      PENDING_CONFIRMATION: "Unconfirmed",
      ACTIVE: "Active",
      BOUNCED: "Bounced",
      COMPLAINED: "Marked as spam",
    },
    fictitious: "fictitious",
    vessel: "Vessel",
    carrier: "Carrier",
    route: "Route",
    routeValue: (from: string, to: string) => `${from} → ${to}`,
    invoice: "Invoice",
    invoiceValue: (number: string, incoterm: string, place: string) => `${number} · ${incoterm} ${place}`,
    regime: "Regime",
  },
  processError: (what: string, when: string) =>
    `Process error: an event of this operation (${what}) could not be processed on ${when} and went to the error queue. The operation no longer waits for it.`,
  risk: {
    title: "Estimated risk",
    level: {
      AT_RISK: "At risk: the dossier is not complete and the arrival is 72 h or less away.",
      ON_TRACK: "On track: the arrival is more than 72 h away.",
      COMPLETE: "Complete: no documents are pending.",
    },
    outstanding: "What is missing and who owes it",
    owedBy: (who: string) => `owed by: ${who}`,
    nobody: "no one assigned",
    assumptionLabel: "Assumption",
    assumption:
      "The potential cost of a delay is estimated from the free days at the port and the daily container demurrage cost the firm declares (unverified secondary sources, editable). It is never a fact: the agent reports it labelled in the escalation.",
  },
  documents: {
    responsible: "Responsible",
    noResponsible: "Unassigned",
    validatedBy: { READER: "Valid by the reading", WAIVER: "Valid by the firm's waiver" },
    versions: "Versions",
    noVersions: "No version has arrived yet.",
    columns: { version: "Version", received: "Received", state: "Status", reading: "Reading", file: "PDF" },
    version: (number: number) => `v${number}`,
    received: (when: string, party: string, channel: string) => `${when} · ${party} ${channel}`,
    confidence: (percent: number) => `confidence ${percent} %`,
    download: "Download PDF",
    downloadLabel: (doc: string, version: number) => `Download the PDF of ${doc}, version ${version}`,
    observations: "Reader observations",
    noObservations: "No observations.",
    expectedFound: (expected: string, found: string) => `expected ${expected} · found ${found}`,
    attempts: (count: number) => (count === 1 ? "1 attempt" : `${count} attempts`),
    matrixDiffers: "Assignment differs from the firm's responsibility matrix: review it",
    waivedBecause: (reason: string) => `Waived: ${reason}`,
    waive: "Waive",
    waiveLabel: (observation: string) => `Waive the observation: ${observation}`,
    unrecognized: (version: number) => `The reader did not recognize version ${version}: a person at the firm classifies it.`,
    classify: "Classify or discard",
  },
  waive: {
    title: "Waive an observation",
    lead: "The observation is no longer requested. If no blocking observations remain, the document becomes valid by the firm's decision and the audit log records it.",
    reason: "Reason",
    reasonHint: "It is recorded in the audit log with your user.",
    submit: "Waive",
    working: "Waiving…",
  },
  classify: {
    title: "Unrecognized document",
    lead: "The reader does not know this PDF. Legajo listo does not read documents: a person classifies it, and it becomes valid by human decision, without a reading.",
    docType: "Classify as",
    submit: "Classify",
    discard: "Discard",
    working: "Saving…",
  },
  pending: {
    lead: "What has to happen at a simulated time, with its reason. “Advance to it” moves the demo clock to that moment.",
    empty: "Nothing pending for this operation.",
    deferred: "Deferred:",
    until: (when: string) => `until ${when}`,
    supplierTime: (supplierWhen: string, arWhen: string) => `${supplierWhen} supplier time (${arWhen} in Argentina)`,
    advance: "Advance to it",
    advanceLabel: (what: string, when: string) => `Advance the clock to ${when}: ${what}`,
    due: "Fires with the next clock advance.",
    tooFar: "More than 14 days away: use the demo clock.",
    busy: "The clock turns on when what is in progress finishes.",
    waitingTitle: "The world is waiting",
  },
  timeline: {
    lead: "WhatsApp and email messages, internal notes of each agent turn, escalations and decisions with their rules, in simulated-time order.",
    empty: "No messages or decisions in this operation yet.",
    note: "Internal turn note (not sent)",
    noteTrigger: (trigger: string) => `triggered by: ${trigger}`,
    escalation: "Escalation to the firm",
    escalationOpen: "Open",
    escalationResolved: (resolution: string) => `Resolved: ${resolution}`,
    route: (from: string, to: string) => `${from} → ${to}`,
    firmMailbox: "Firm mailbox",
    subject: (subject: string) => `Subject: ${subject}`,
    template: "Approved template",
    deferredUntil: (when: string) => `Deferred until ${when}`,
    buttons: "Buttons",
    attachment: (size: string, status: string) => `PDF attachment (${size}) · ${status}`,
    attachmentStatus: { ACCEPTED: "accepted", REJECTED: "rejected", QUARANTINED: "quarantined" },
    by: (actor: string) => `by ${actor}`,
  },
  approval: {
    approve: "Approve dossier",
    notReady: "Turns on when the dossier is ready for review (all three documents valid).",
    title: "Approve the dossier",
    lead: "Approval is always human. Review the documents and how each observation was resolved; on approval, the importer gets the notice on WhatsApp.",
    documents: "Documents",
    observations: "Observations and how they were resolved",
    noObservations: "The reader left no observations.",
    submit: "Approve",
    working: "Approving…",
    done: "Dossier approved. The notice to the importer goes out through the same outbound pipeline.",
    stepUp: "Approving and reopening require having signed in with your password in the last 15 minutes.",
  },
  reopen: {
    open: "Reopen dossier",
    title: "Reopen the dossier",
    lead: "The dossier is open again and the agent picks up what is pending; once complete, it goes back to review.",
    reason: "Reason",
    reasonHint: "For example: a new certificate arrived.",
    submit: "Reopen",
    working: "Reopening…",
    done: "Dossier reopened.",
  },
  conversation: {
    take: "Take over the conversation",
    release: "Hand back to the agent",
    working: "Saving…",
    takeHint: "While the firm holds the conversation, the agent does not write. Take it over to write to the importer.",
    write: "Write to the importer",
    title: "Write to the importer on WhatsApp",
    text: "Message",
    empty: "Write the message.",
    textHint: (max: number) => `Up to ${max} characters. No links, contacts or sensitive data: the contact policy checks it before sending.`,
    windowClosed: "More than 24 h have passed since the importer's last message: WhatsApp only allows approved templates.",
    approvedScope: "The dossier is approved: the importer only receives the approval notice and the dispatch statuses.",
    template: "Template",
    templates: {
      legajo_escalado: "A person from the firm takes over this chat",
      legajo_recordatorio: "Reminder of the missing documents",
    } satisfies Record<BrokerTemplate, string>,
    send: "Send",
    sending: "Sending…",
    sent: "Message on its way: it goes out through the outbound pipeline and shows up in the timeline.",
  },
  reasonRequired: "Write the reason.",
  close: "Close",
} satisfies DossierCopy;
