// Spanish texts of the dossier view (docs/design-brief.md §6, row 2). Rioplatense Spanish, for the firm;
// the assumptions of the risk are always labelled "supuesto" (CLAUDE.md, "Supuestos rotulados"). The
// English ones (copy-en.ts) have exactly this shape; copy.ts composes both (copy/localized.ts).
import type { Widen } from "../../copy/localized";
import type { BrokerTemplate } from "./dossier-model";

export const es = {
  notFound: {
    title: "Esta operación no existe",
    lead: "Revisá el enlace o volvé a la lista de operaciones.",
  },
  back: "Volver a operaciones",
  actions: "Acciones del legajo",
  heading: (number: string, importer: string, supplier: string) => `Operación ${number} · ${importer} · ${supplier}`,
  sections: {
    nav: "Secciones del legajo",
    summary: "Resumen",
    documents: "Documentos",
    pending: "Pendientes",
    timeline: "Línea de tiempo",
  },
  facts: {
    eta: "ETA",
    toArrival: "Al arribo",
    dossier: "Legajo",
    control: "Conversación",
    dispatch: "Despacho",
    risk: "Riesgo",
    toArrivalValue: (days: number, hours: number) => (days > 0 ? `${days} d ${hours} h` : `${hours} h`),
    arrived: "Ya arribó",
    unknown: "—",
  },
  parties: {
    title: "Partes y datos de la operación",
    importer: "Importador",
    supplier: "Proveedor",
    contact: (name: string, phone: string) => `${name} · ${phone}`,
    supplierZone: (country: string, zone: string) => `${country} · hora local: ${zone}`,
    contacts: "Contactos del proveedor",
    noContacts: "Sin contactos registrados",
    contactStatus: {
      PENDING_CONFIRMATION: "Sin confirmar",
      ACTIVE: "Activo",
      BOUNCED: "Rebotó",
      COMPLAINED: "Marcó como no deseado",
    } as Readonly<Record<string, string>>,
    fictitious: "ficticio",
    vessel: "Buque",
    carrier: "Transportista",
    route: "Ruta",
    routeValue: (from: string, to: string) => `${from} → ${to}`,
    invoice: "Factura",
    invoiceValue: (number: string, incoterm: string, place: string) => `${number} · ${incoterm} ${place}`,
    regime: "Régimen",
  },
  processError: (what: string, when: string) =>
    `Con error de proceso: un evento de esta operación (${what}) no se pudo procesar el ${when} y quedó en la cola de errores. La operación ya no lo espera.`,
  risk: {
    title: "Riesgo estimado",
    level: {
      AT_RISK: "En riesgo: el legajo no está completo y faltan 72 h o menos para el arribo.",
      ON_TRACK: "En plazo: faltan más de 72 h para el arribo.",
      COMPLETE: "Completo: no hay documentos pendientes.",
    },
    outstanding: "Qué falta y quién lo debe",
    owedBy: (who: string) => `lo debe: ${who}`,
    nobody: "sin responsable asignado",
    assumptionLabel: "Supuesto",
    assumption:
      "El costo potencial de una demora se estima con los días libres en el puerto y el costo diario de demora de contenedor que declara el estudio (fuentes secundarias no verificadas, editables). Nunca es un hecho: el agente lo informa rotulado en el escalamiento.",
  },
  documents: {
    responsible: "Responsable",
    noResponsible: "Sin asignar",
    validatedBy: { READER: "Válido por la lectura", WAIVER: "Válido por dispensa del estudio" } as Readonly<Record<string, string>>,
    versions: "Versiones",
    noVersions: "Todavía no llegó ninguna versión.",
    columns: { version: "Versión", received: "Recibida", state: "Estado", reading: "Lectura", file: "PDF" },
    version: (number: number) => `v${number}`,
    received: (when: string, party: string, channel: string) => `${when} · ${party} ${channel}`,
    confidence: (percent: number) => `confianza ${percent} %`,
    download: "Descargar PDF",
    downloadLabel: (doc: string, version: number) => `Descargar el PDF de ${doc}, versión ${version}`,
    observations: "Observaciones del lector",
    noObservations: "Sin observaciones.",
    expectedFound: (expected: string, found: string) => `esperado ${expected} · encontrado ${found}`,
    attempts: (count: number) => (count === 1 ? "1 intento" : `${count} intentos`),
    matrixDiffers: "Asignación distinta de la matriz del estudio: revisar",
    waivedBecause: (reason: string) => `Dispensada: ${reason}`,
    waive: "Dispensar",
    waiveLabel: (observation: string) => `Dispensar la observación: ${observation}`,
    unrecognized: (version: number) => `La versión ${version} no la reconoció el lector: la clasifica una persona del estudio.`,
    classify: "Clasificar o descartar",
  },
  waive: {
    title: "Dispensar una observación",
    lead: "La observación deja de pedirse. Si no quedan observaciones bloqueantes, el documento queda válido por decisión del estudio y la bitácora lo registra.",
    reason: "Motivo",
    reasonHint: "Queda en la bitácora con tu usuario.",
    submit: "Dispensar",
    working: "Dispensando…",
  },
  classify: {
    title: "Documento no reconocido",
    lead: "El lector no conoce este PDF. Legajo listo no lee documentos: lo clasifica una persona, y queda válido por decisión humana, sin lectura.",
    docType: "Clasificar como",
    submit: "Clasificar",
    discard: "Descartar",
    working: "Guardando…",
  },
  pending: {
    lead: "Lo que tiene que pasar en una hora simulada, con su motivo. «Avanzar hasta ahí» mueve el reloj de demo hasta ese momento.",
    empty: "Nada pendiente para esta operación.",
    deferred: "Diferido:",
    until: (when: string) => `hasta ${when}`,
    supplierTime: (supplierWhen: string, arWhen: string) => `${supplierWhen} hora del proveedor (${arWhen} en Argentina)`,
    advance: "Avanzar hasta ahí",
    advanceLabel: (what: string, when: string) => `Avanzar el reloj hasta ${when}: ${what}`,
    due: "Se dispara con el próximo avance del reloj.",
    tooFar: "Más de 14 días: usá el reloj de demo.",
    busy: "El reloj se habilita cuando termina lo que está en curso.",
    waitingTitle: "El mundo está esperando",
  },
  timeline: {
    lead: "Mensajes por WhatsApp y email, notas internas de cada turno del agente, escalamientos y decisiones con sus reglas, en orden de hora simulada.",
    empty: "Todavía no hay mensajes ni decisiones en esta operación.",
    note: "Nota interna del turno (no se envía)",
    noteTrigger: (trigger: string) => `disparado por: ${trigger}`,
    escalation: "Escalamiento al estudio",
    escalationOpen: "Abierto",
    escalationResolved: (resolution: string) => `Resuelto: ${resolution}`,
    route: (from: string, to: string) => `${from} → ${to}`,
    firmMailbox: "Buzón del estudio",
    subject: (subject: string) => `Asunto: ${subject}`,
    template: "Plantilla aprobada",
    deferredUntil: (when: string) => `Diferido hasta ${when}`,
    buttons: "Botones",
    attachment: (size: string, status: string) => `Adjunto PDF (${size}) · ${status}`,
    attachmentStatus: { ACCEPTED: "aceptado", REJECTED: "rechazado", QUARANTINED: "en cuarentena" } as Readonly<Record<string, string>>,
    by: (actor: string) => `por ${actor}`,
  },
  approval: {
    approve: "Aprobar legajo",
    notReady: "Se habilita cuando el legajo está listo para revisión (los tres documentos válidos).",
    title: "Aprobar el legajo",
    lead: "La aprobación es siempre humana. Revisá los documentos y cómo se resolvió cada observación; al aprobar, el importador recibe el aviso por WhatsApp.",
    documents: "Documentos",
    observations: "Observaciones y cómo se resolvieron",
    noObservations: "El lector no dejó observaciones.",
    submit: "Aprobar",
    working: "Aprobando…",
    done: "Legajo aprobado. El aviso al importador sale por el mismo pipeline de salida.",
    stepUp: "Aprobar y reabrir piden haber ingresado con tu contraseña en los últimos 15 minutos.",
  },
  reopen: {
    open: "Reabrir legajo",
    title: "Reabrir el legajo",
    lead: "El legajo vuelve a estar abierto y el agente retoma lo pendiente; al completarse, pasa de nuevo a revisión.",
    reason: "Motivo",
    reasonHint: "Por ejemplo: llegó un certificado nuevo.",
    submit: "Reabrir",
    working: "Reabriendo…",
    done: "Legajo reabierto.",
  },
  conversation: {
    take: "Tomar conversación",
    release: "Devolver al agente",
    working: "Guardando…",
    takeHint: "Mientras el estudio tiene la conversación, el agente no escribe. Tomala para escribirle al importador.",
    write: "Escribir al importador",
    title: "Escribir al importador por WhatsApp",
    text: "Mensaje",
    empty: "Escribí el mensaje.",
    textHint: (max: number) => `Hasta ${max} caracteres. Sin enlaces, contactos ni datos sensibles: la política de contacto lo revisa antes de enviar.`,
    windowClosed: "Pasaron más de 24 h desde el último mensaje del importador: WhatsApp solo admite plantillas aprobadas.",
    approvedScope: "El legajo está aprobado: al importador solo le llegan el aviso de aprobación y los estados del despacho.",
    template: "Plantilla",
    templates: {
      legajo_escalado: "Una persona del estudio sigue por este chat",
      legajo_recordatorio: "Recordatorio de los documentos que faltan",
    } satisfies Record<BrokerTemplate, string>,
    send: "Enviar",
    sending: "Enviando…",
    sent: "Mensaje en camino: sale por el pipeline de salida y aparece en la línea de tiempo.",
  },
  reasonRequired: "Escribí el motivo.",
  close: "Cerrar",
} as const;

export type DossierCopy = Widen<typeof es>;
