// What the firm reads for each code of an operation, its dossier and its timeline, in rioplatense
// Spanish (CONTEXT.md vocabulary). The English ones (labels-en.ts) have exactly this shape; labels.ts
// composes both (copy/localized.ts) and is the module the views import.
import type {
  AuditDecision,
  Channel,
  ConversationControl,
  CustomsChannel,
  DispatchStatus,
  DocStatus,
  DocType,
  DocumentSourceChannel,
  DossierStatus,
  EscalationReason,
  MessageKind,
  MilestoneName,
  ObservationCode,
  ObservationSeverity,
  ObservationStatus,
  OperationEventType,
  Party,
  ReadingStatus,
  TimerKind,
  TurnTrigger,
} from "@legajo/shared";
import type { Widen } from "../../copy/localized";
import type { Risk } from "./risk";

export const es = {
  docType: {
    COMMERCIAL_INVOICE: "Factura comercial",
    PACKING_LIST: "Packing list",
    CERTIFICATE_OF_ORIGIN: "Certificado de origen",
  } satisfies Record<DocType, string>,
  docStatus: {
    MISSING: "Faltante",
    RECEIVED: "Recibido",
    WITH_OBSERVATION: "Con observación",
    VALID: "Válido",
  } satisfies Record<DocStatus, string>,
  dossierStatus: {
    OPEN: "Abierto",
    READY_FOR_REVIEW: "Listo para revisión",
    APPROVED: "Aprobado",
    REOPENED: "Reabierto",
  } satisfies Record<DossierStatus, string>,
  risk: {
    AT_RISK: "En riesgo",
    ON_TRACK: "En plazo",
    COMPLETE: "Completo",
  } satisfies Record<Risk, string>,
  party: {
    IMPORTER: "Importador",
    SUPPLIER: "Proveedor",
    BROKER: "Estudio",
  } satisfies Record<Party, string>,
  control: {
    AGENT: "La lleva el agente",
    BROKER: "La tomó el estudio",
  } satisfies Record<ConversationControl, string>,
  escalationReason: {
    MISSING_AT_ETA_48H: "Faltan documentos a 48 h del arribo",
    OBSERVATION_ATTEMPTS: "Observación sin corregir tras dos intentos",
    OUT_OF_CHECKLIST: "Pregunta fuera del checklist",
    IMPORTER_ASKED: "El importador pidió hablar con una persona",
    UNRECOGNIZED_DOCUMENT: "Documento no reconocido por el lector",
    NO_VALID_CONTACT: "Proveedor sin contacto válido",
    UNTRUSTED_SENDER: "Remitente no verificado",
    OPTED_OUT: "El importador pidió no recibir avisos",
    READER_UNAVAILABLE: "El lector documental no respondió",
    OTHER: "Otro motivo",
  } satisfies Record<EscalationReason, string>,
  observationStatus: {
    OPEN: "Abierta",
    CORRECTION_REQUESTED: "Corrección pedida",
    RESOLVED: "Resuelta",
    ESCALATED: "Escalada al estudio",
    WAIVED_BY_BROKER: "Dispensada por el estudio",
  } satisfies Record<ObservationStatus, string>,
  /** What the reader found, as the console names it (the reader's code stays its own, ADR-0003). */
  observationCode: {
    GROSS_WEIGHT_MISMATCH: "Peso bruto distinto del de la factura",
    NET_WEIGHT_MISMATCH: "Peso neto distinto del de la factura",
    INVOICE_NUMBER_MISMATCH: "Número de factura distinto",
    INCOTERM_MISMATCH: "Incoterm distinto del de la operación",
    BUYER_DATA_MISMATCH: "Datos del comprador distintos del registro",
    ORIGIN_MISMATCH: "País de origen distinto del de la factura",
    PACKAGES_MISMATCH: "Cantidad de bultos distinta de la factura",
    MISSING_SIGNATURE: "Falta la firma",
    MISSING_STAMP: "Falta el sello",
    LOW_CONFIDENCE: "Lectura de baja confianza",
  } satisfies Record<ObservationCode, string>,
  severity: {
    BLOCKING: "Bloqueante",
    WARNING: "Advertencia",
  } satisfies Record<ObservationSeverity, string>,
  readingStatus: {
    RECOGNIZED: "Reconocido por el lector",
    UNRECOGNIZED: "No reconocido por el lector",
    ERROR: "El lector devolvió un error",
  } satisfies Record<ReadingStatus, string>,
  /** States of a document version; any other code is not shown. */
  versionState: {
    RECEIVED: "Recibida, esperando lectura",
    READ: "Leída",
    UNRECOGNIZED: "No reconocida: la clasifica el estudio",
    CLASSIFIED: "Clasificada por el estudio",
    DISCARDED: "Descartada por el estudio",
    READER_UNAVAILABLE: "El lector no respondió",
  },
  sourceChannel: {
    EMAIL: "por email",
    WHATSAPP: "por WhatsApp",
    UPLOAD_LINK: "por el link de carga",
    CONSOLE: "desde la consola",
  } satisfies Record<DocumentSourceChannel, string>,
  channel: {
    WHATSAPP: "WhatsApp",
    EMAIL: "Email",
    CONSOLE: "Consola",
  } satisfies Record<Channel, string>,
  messageKind: {
    DOCS_REQUEST: "Pedido de documentos",
    REMINDER: "Recordatorio",
    CORRECTION_REQUEST: "Pedido de corrección",
    NO_ACTION_NEEDED: "Aviso: no tiene que hacer nada",
    CONTACT_REQUEST: "Pedido de otro contacto",
    CONTACT_CONFIRMATION: "Confirmación de contacto",
    UPLOAD_LINK: "Link de carga",
    ETA_CHANGE: "Nuevo plazo por cambio de ETA",
    ESCALATION_NOTICE: "Aviso de traspaso al estudio",
    ESCALATION: "Escalamiento al estudio",
    APPROVAL_NOTICE: "Aviso de aprobación",
    DISPATCH_STATUS: "Estado del despacho",
    REPLY: "Respuesta",
    BROKER_MESSAGE: "Mensaje del estudio",
    OPT_OUT_CONFIRMATION: "Confirmación de baja",
    OPERATION_CHOICE: "Elección de operación",
  } satisfies Record<MessageKind, string>,
  /** Statuses of a message; any other code is not shown. */
  messageStatus: {
    RECEIVED: "Recibido",
    QUEUED: "En cola",
    DEFERRED: "Diferido",
    SENT: "Enviado",
    DELIVERED: "Entregado",
    READ: "Leído",
    DELAYED: "Demorado",
    FAILED: "No se pudo enviar",
    BOUNCED: "Rebotó",
    COMPLAINED: "Marcado como no deseado",
    QUARANTINED: "En cuarentena",
    DISCARDED: "Descartado",
  },
  timerKind: {
    MILESTONE: "Hito",
    DEFERRED_SEND: "Envío diferido",
    FOLLOWUP_DUE: "Seguimiento agendado por el agente",
    SIM_REPLY: "Esperando respuesta del proveedor por SES",
    READER_RETRY: "Reintento del lector documental",
    CONTACT_CHECK: "Control de contacto después de un rebote",
    BOUNCE_RETRY: "Reenvío después de un rebote transitorio",
  } satisfies Record<TimerKind, string>,
  milestone: {
    DOCS_REQUEST: "Pedido inicial (ETA − 7 días)",
    FOLLOWUP: "Recordatorio (ETA − 5 días)",
    FOLLOWUP_FINAL: "Último recordatorio (ETA − 3 días)",
    ESCALATION: "Escalamiento si faltan documentos (ETA − 48 h)",
    ARRIVAL: "Arribo (ETA)",
  } satisfies Record<MilestoneName, string>,
  dispatch: {
    NONE: "Sin novedades de aduana",
    OFICIALIZADO: "Oficializado",
    CANAL_ASIGNADO: "Canal asignado",
    LIBERADO: "Liberado",
  } satisfies Record<DispatchStatus, string>,
  customsChannel: {
    VERDE: "verde",
    NARANJA: "naranja",
    ROJO: "rojo",
  } satisfies Record<CustomsChannel, string>,
  decision: {
    ALLOW: "Permitido",
    DENY: "Denegado",
    DEFER: "Diferido",
    ACTION: "Acción",
    VIOLATION: "Violación de política",
  } satisfies Record<AuditDecision, string>,
  /** Actions of the audit log an operation's timeline shows; any other reads as its decision label. */
  auditAction: {
    OPERATION_CREATED: "Operación creada desde la plataforma",
    MILESTONE_FIRED: "Hito disparado",
    MILESTONE_SKIPPED: "Hito omitido",
    TIMER_FIRED: "Temporizador disparado",
    DOCUMENT_READ: "Documento leído por el lector",
    ASSIGN_RESPONSIBLE: "Responsable asignado",
    WAIVED: "Observación dispensada",
    APPROVED: "Legajo aprobado",
    REOPENED: "Legajo reabierto",
    TAKEOVER: "El estudio tomó la conversación",
    RELEASE: "Conversación devuelta al agente",
    ETA_RESCHEDULED: "Hitos reprogramados por cambio de ETA",
    CONTACT_CONFIRMED: "Contacto del proveedor confirmado",
    CONSENT_GRANTED: "Opt-in de WhatsApp registrado",
    CONSENT_REVOKED: "Opt-in de WhatsApp revocado",
    ESCALATION_RESOLVED: "Escalamiento resuelto",
    TURN_SKIPPED_CONTROL_BROKER: "Sin turno del agente: la conversación la tiene el estudio",
    GUARDRAIL_BLOCK: "Mensaje bloqueado por el guardrail de entrada",
    GUARDRAIL_MASK: "Datos sensibles enmascarados por el guardrail",
    EVENT_DEAD_LETTERED: "Evento sin procesar (cola de errores)",
    SIM_REPLY: "Respuesta del simulador de proveedor",
    AGENT_FALLBACK: "Mensaje de respaldo del sistema",
    TURN_CAP: "Tope de turnos del estudio alcanzado",
    AUTO_REPLY_IGNORED: "Respuesta automática ignorada",
    SEND_WHATSAPP: "Envío por WhatsApp",
    SEND_EMAIL: "Envío por email",
    CLASSIFIED: "Documento clasificado por el estudio",
    DISCARDED: "Documento descartado por el estudio",
  },
  /** Actors other than a broker (`BROKER:<id>` reads as the firm, labels.ts). */
  actor: {
    AGENT: "Agente",
    SYSTEM: "Sistema",
    IMPORTER: "Importador",
    SUPPLIER: "Proveedor",
    SEED: "Historia de la demo",
    QA: "Pruebas",
  },
  /** Codes a timer may carry as its reason besides a rule id; any other code is not shown. */
  timerReason: {
    READER_UNAVAILABLE: "el lector documental no respondió",
    DOSSIER_COMPLETE: "el legajo ya está completo",
  },
  turnTrigger: {
    IMPORTER_MESSAGE: "mensaje del importador",
    SUPPLIER_EMAIL: "email del proveedor",
    DOCUMENT_READ: "lectura de un documento",
    MILESTONE: "hito",
    ETA_CHANGED: "cambio de ETA",
    EMAIL_BOUNCED: "rebote de un email",
    CONTACT_CONFIRMED: "contacto confirmado",
    UPLOAD_COMPLETED: "carga completa por el link",
    BROKER_RELEASED: "el estudio devolvió la conversación",
    FOLLOWUP_DUE: "seguimiento agendado",
  } satisfies Record<TurnTrigger, string>,
  eventType: {
    INTAKE_DOCUMENT: "lectura de un documento",
    AGENT_TURN: "turno del agente",
    TIMER: "temporizador",
    ETA_CHANGED: "cambio de ETA",
    DISPATCH_STATUS: "estado del despacho",
    EMAIL_EVENT: "evento de email",
    OUTBOUND_SEND: "envío ordenado por el estudio",
    ESCALATE: "escalamiento",
    HEALTH_PROBE: "prueba de salud",
    POISON: "evento de prueba",
  } satisfies Record<OperationEventType, string>,
} as const;

export type LabelsCopy = Widen<typeof es>;
