// English labels for each code of an operation, its dossier and its timeline, key by key the Spanish
// ones of labels-es.ts (`satisfies` refuses a missing, extra or differently typed key).
import type {
  AuditDecision,
  Channel,
  ConversationControl,
  CustomsChannel,
  DispatchStatus,
  DocStatus,
  DocType,
  DocumentSourceChannel,
  DossierStatus,
  EscalationReason,
  MessageKind,
  MilestoneName,
  ObservationCode,
  ObservationSeverity,
  ObservationStatus,
  OperationEventType,
  Party,
  ReadingStatus,
  TimerKind,
  TurnTrigger,
} from "@legajo/shared";
import type { LabelsCopy } from "./labels-es";
import type { Risk } from "./risk";

export const en = {
  docType: {
    COMMERCIAL_INVOICE: "Commercial invoice",
    PACKING_LIST: "Packing list",
    CERTIFICATE_OF_ORIGIN: "Certificate of origin",
  } satisfies Record<DocType, string>,
  docStatus: {
    MISSING: "Missing",
    RECEIVED: "Received",
    WITH_OBSERVATION: "With observation",
    VALID: "Valid",
  } satisfies Record<DocStatus, string>,
  dossierStatus: {
    OPEN: "Open",
    READY_FOR_REVIEW: "Ready for review",
    APPROVED: "Approved",
    REOPENED: "Reopened",
  } satisfies Record<DossierStatus, string>,
  risk: {
    AT_RISK: "At risk",
    ON_TRACK: "On track",
    COMPLETE: "Complete",
  } satisfies Record<Risk, string>,
  party: {
    IMPORTER: "Importer",
    SUPPLIER: "Supplier",
    BROKER: "Firm",
  } satisfies Record<Party, string>,
  control: {
    AGENT: "Handled by the agent",
    BROKER: "Taken over by the firm",
  } satisfies Record<ConversationControl, string>,
  escalationReason: {
    MISSING_AT_ETA_48H: "Documents missing 48 h before arrival",
    OBSERVATION_ATTEMPTS: "Observation not corrected after two attempts",
    OUT_OF_CHECKLIST: "Question outside the checklist",
    IMPORTER_ASKED: "The importer asked to talk to a person",
    UNRECOGNIZED_DOCUMENT: "Document not recognized by the reader",
    NO_VALID_CONTACT: "Supplier without a valid contact",
    UNTRUSTED_SENDER: "Unverified sender",
    OPTED_OUT: "The importer opted out of notices",
    READER_UNAVAILABLE: "The document reader did not respond",
    OTHER: "Other reason",
  } satisfies Record<EscalationReason, string>,
  observationStatus: {
    OPEN: "Open",
    CORRECTION_REQUESTED: "Correction requested",
    RESOLVED: "Resolved",
    ESCALATED: "Escalated to the firm",
    WAIVED_BY_BROKER: "Waived by the firm",
  } satisfies Record<ObservationStatus, string>,
  observationCode: {
    GROSS_WEIGHT_MISMATCH: "Gross weight differs from the invoice",
    NET_WEIGHT_MISMATCH: "Net weight differs from the invoice",
    INVOICE_NUMBER_MISMATCH: "Different invoice number",
    INCOTERM_MISMATCH: "Incoterm differs from the operation's",
    BUYER_DATA_MISMATCH: "Buyer details differ from the records",
    ORIGIN_MISMATCH: "Country of origin differs from the invoice",
    PACKAGES_MISMATCH: "Number of packages differs from the invoice",
    MISSING_SIGNATURE: "Signature missing",
    MISSING_STAMP: "Stamp missing",
    LOW_CONFIDENCE: "Low-confidence reading",
  } satisfies Record<ObservationCode, string>,
  severity: {
    BLOCKING: "Blocking",
    WARNING: "Warning",
  } satisfies Record<ObservationSeverity, string>,
  readingStatus: {
    RECOGNIZED: "Recognized by the reader",
    UNRECOGNIZED: "Not recognized by the reader",
    ERROR: "The reader returned an error",
  } satisfies Record<ReadingStatus, string>,
  versionState: {
    RECEIVED: "Received, waiting for the reading",
    READ: "Read",
    UNRECOGNIZED: "Not recognized: the firm classifies it",
    CLASSIFIED: "Classified by the firm",
    DISCARDED: "Discarded by the firm",
    READER_UNAVAILABLE: "The reader did not respond",
  },
  sourceChannel: {
    EMAIL: "by email",
    WHATSAPP: "on WhatsApp",
    UPLOAD_LINK: "through the upload link",
    CONSOLE: "from the console",
  } satisfies Record<DocumentSourceChannel, string>,
  channel: {
    WHATSAPP: "WhatsApp",
    EMAIL: "Email",
    CONSOLE: "Console",
  } satisfies Record<Channel, string>,
  messageKind: {
    DOCS_REQUEST: "Documents request",
    REMINDER: "Reminder",
    CORRECTION_REQUEST: "Correction request",
    NO_ACTION_NEEDED: "Notice: nothing to do",
    CONTACT_REQUEST: "Request for another contact",
    CONTACT_CONFIRMATION: "Contact confirmation",
    UPLOAD_LINK: "Upload link",
    ETA_CHANGE: "New deadline after an ETA change",
    ESCALATION_NOTICE: "Handover-to-the-firm notice",
    ESCALATION: "Escalation to the firm",
    APPROVAL_NOTICE: "Approval notice",
    DISPATCH_STATUS: "Dispatch status",
    REPLY: "Reply",
    BROKER_MESSAGE: "Message from the firm",
    OPT_OUT_CONFIRMATION: "Opt-out confirmation",
    OPERATION_CHOICE: "Operation choice",
  } satisfies Record<MessageKind, string>,
  messageStatus: {
    RECEIVED: "Received",
    QUEUED: "Queued",
    DEFERRED: "Deferred",
    SENT: "Sent",
    DELIVERED: "Delivered",
    READ: "Read",
    DELAYED: "Delayed",
    FAILED: "Could not be sent",
    BOUNCED: "Bounced",
    COMPLAINED: "Marked as spam",
    QUARANTINED: "Quarantined",
    DISCARDED: "Discarded",
  },
  timerKind: {
    MILESTONE: "Milestone",
    DEFERRED_SEND: "Deferred send",
    FOLLOWUP_DUE: "Follow-up scheduled by the agent",
    SIM_REPLY: "Waiting for the supplier's reply through SES",
    READER_RETRY: "Document reader retry",
    CONTACT_CHECK: "Contact check after a bounce",
    BOUNCE_RETRY: "Resend after a transient bounce",
  } satisfies Record<TimerKind, string>,
  milestone: {
    DOCS_REQUEST: "Initial request (ETA − 7 days)",
    FOLLOWUP: "Reminder (ETA − 5 days)",
    FOLLOWUP_FINAL: "Last reminder (ETA − 3 days)",
    ESCALATION: "Escalation if documents are missing (ETA − 48 h)",
    ARRIVAL: "Arrival (ETA)",
  } satisfies Record<MilestoneName, string>,
  dispatch: {
    NONE: "No customs updates",
    OFICIALIZADO: "Officialized",
    CANAL_ASIGNADO: "Channel assigned",
    LIBERADO: "Released",
  } satisfies Record<DispatchStatus, string>,
  customsChannel: {
    VERDE: "green",
    NARANJA: "orange",
    ROJO: "red",
  } satisfies Record<CustomsChannel, string>,
  decision: {
    ALLOW: "Allowed",
    DENY: "Denied",
    DEFER: "Deferred",
    ACTION: "Action",
    VIOLATION: "Policy violation",
  } satisfies Record<AuditDecision, string>,
  auditAction: {
    OPERATION_CREATED: "Operation created from the platform",
    MILESTONE_FIRED: "Milestone fired",
    MILESTONE_SKIPPED: "Milestone skipped",
    TIMER_FIRED: "Timer fired",
    DOCUMENT_READ: "Document read by the reader",
    ASSIGN_RESPONSIBLE: "Responsible assigned",
    WAIVED: "Observation waived",
    APPROVED: "Dossier approved",
    REOPENED: "Dossier reopened",
    TAKEOVER: "The firm took over the conversation",
    RELEASE: "Conversation handed back to the agent",
    ETA_RESCHEDULED: "Milestones rescheduled after an ETA change",
    CONTACT_CONFIRMED: "Supplier contact confirmed",
    CONSENT_GRANTED: "WhatsApp opt-in recorded",
    CONSENT_REVOKED: "WhatsApp opt-in revoked",
    ESCALATION_RESOLVED: "Escalation resolved",
    TURN_SKIPPED_CONTROL_BROKER: "No agent turn: the firm holds the conversation",
    GUARDRAIL_BLOCK: "Message blocked by the input guardrail",
    GUARDRAIL_MASK: "Sensitive data masked by the guardrail",
    EVENT_DEAD_LETTERED: "Unprocessed event (error queue)",
    SIM_REPLY: "Reply from the supplier simulator",
    AGENT_FALLBACK: "System fallback message",
    TURN_CAP: "The firm's turn cap was reached",
    AUTO_REPLY_IGNORED: "Automatic reply ignored",
    SEND_WHATSAPP: "Sent on WhatsApp",
    SEND_EMAIL: "Sent by email",
    CLASSIFIED: "Document classified by the firm",
    DISCARDED: "Document discarded by the firm",
  },
  actor: {
    AGENT: "Agent",
    SYSTEM: "System",
    IMPORTER: "Importer",
    SUPPLIER: "Supplier",
    SEED: "Demo story",
    QA: "Tests",
  },
  timerReason: {
    READER_UNAVAILABLE: "the document reader did not respond",
    DOSSIER_COMPLETE: "the dossier is already complete",
  },
  turnTrigger: {
    IMPORTER_MESSAGE: "importer message",
    SUPPLIER_EMAIL: "supplier email",
    DOCUMENT_READ: "a document reading",
    MILESTONE: "milestone",
    ETA_CHANGED: "ETA change",
    EMAIL_BOUNCED: "an email bounce",
    CONTACT_CONFIRMED: "contact confirmed",
    UPLOAD_COMPLETED: "upload completed through the link",
    BROKER_RELEASED: "the firm handed back the conversation",
    FOLLOWUP_DUE: "scheduled follow-up",
  } satisfies Record<TurnTrigger, string>,
  eventType: {
    INTAKE_DOCUMENT: "a document reading",
    AGENT_TURN: "agent turn",
    TIMER: "timer",
    ETA_CHANGED: "ETA change",
    DISPATCH_STATUS: "dispatch status",
    EMAIL_EVENT: "email event",
    OUTBOUND_SEND: "send ordered by the firm",
    ESCALATE: "escalation",
    HEALTH_PROBE: "health probe",
    POISON: "test event",
  } satisfies Record<OperationEventType, string>,
} satisfies LabelsCopy;
